grafana:
  adminPassword: "admin"
  resources:
    requests: { cpu: 50m, memory: 100Mi }
    limits: { cpu: 100m, memory: 200Mi }
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: [""]
    path: /grafana
    pathType: Prefix

prometheus:
  prometheusSpec:
    retention: 6h
    resources:
      requests: { cpu: 100m, memory: 200Mi }
      limits: { cpu: 200m, memory: 400Mi }
    storageSpec: { emptyDir: {} }
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: [""]
    path: ["/prometheus"]
    pathType: Prefix

alertmanager:
  resources: { requests: { cpu: 10m, memory: 50Mi }, limits: { cpu: 50m, memory: 100Mi } }
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: [""]
    path: ["/alertmanager"]
    pathType: Prefix

prometheus-node-exporter:
  resources: { requests: { cpu: 10m, memory: 30Mi }, limits: { cpu: 50m, memory: 60Mi } }
  tolerations: [{ operator: "Exists" }]

kube-state-metrics:
  resources: { requests: { cpu: 10m, memory: 50Mi }, limits: { cpu: 50m, memory: 100Mi } }

kubeEtcd: { enabled: false }
kubeScheduler: { enabled: false }
kubeProxy: { enabled: false }
