grafana:
  adminPassword: "admin"
  resources:
    requests: { cpu: 50m, memory: 150Mi }
    limits: { cpu: 200m, memory: 400Mi }
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: [""]
    paths: ["/grafana"]
    pathType: Prefix

prometheus:
  prometheusSpec:
    retention: 1h
    resources:
      requests: { cpu: 50m, memory: 100Mi }
      limits: { cpu: 100m, memory: 200Mi }
    storageSpec: { emptyDir: {} }
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: [""]
    paths: ["/prometheus"]
    pathType: Prefix

alertmanager:
  alertmanagerSpec:
    resources:
      requests: { cpu: 10m, memory: 20Mi }
      limits: { cpu: 30m, memory: 50Mi }
    storage: { emptyDir: {} }
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: [""]
    paths: ["/alertmanager"]
    pathType: Prefix

prometheus-node-exporter:
  resources: { requests: { cpu: 10m, memory: 20Mi }, limits: { cpu: 30m, memory: 40Mi } }
  tolerations: [{ operator: "Exists" }]

kube-state-metrics:
  resources: { requests: { cpu: 10m, memory: 30Mi }, limits: { cpu: 30m, memory: 60Mi } }

kubeEtcd: { enabled: false }
kubeScheduler: { enabled: false }
kubeProxy: { enabled: false }
